package com.bluetooth.le._enum;

public enum CharacteristicProperty {
    PROPERTY_BROADCAST,
    PROPERTY_READ,
    PROPERTY_WRITE_NO_RESPONSE,
    PROPERTY_WRITE,
    PROPERTY_NOTIFY,
    PROPERTY_INDICATE,
    PROPERTY_SIGNED_WRITE,
    PROPERTY_EXTENDED_PROPS,
    WRITE_TYPE_DEFAULT,
    WRITE_TYPE_NO_RESPONSE,
    WRITE_TYPE_SIGNED
}
